// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcknowledgeTerminalOutput(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Desktop']['AcknowledgeTerminalOutput'](arg1, arg2, arg3, arg4, arg5);
}

export function ActivateTerminal(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['ActivateTerminal'](arg1, arg2, arg3);
}

export function AttachFrontend(arg1) {
  return window['go']['bridge']['Desktop']['AttachFrontend'](arg1);
}

export function CancelTransfer(arg1, arg2) {
  return window['go']['bridge']['Desktop']['CancelTransfer'](arg1, arg2);
}

export function ChmodRemotePath(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Desktop']['ChmodRemotePath'](arg1, arg2, arg3, arg4);
}

export function CloseSFTP(arg1, arg2) {
  return window['go']['bridge']['Desktop']['CloseSFTP'](arg1, arg2);
}

export function CloseTerminal(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['CloseTerminal'](arg1, arg2, arg3);
}

export function ConfirmApplicationClose(arg1) {
  return window['go']['bridge']['Desktop']['ConfirmApplicationClose'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['bridge']['Desktop']['CreateProfile'](arg1);
}

export function CreateRemoteDirectory(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['CreateRemoteDirectory'](arg1, arg2, arg3);
}

export function CreateRemotePathFavorite(arg1, arg2) {
  return window['go']['bridge']['Desktop']['CreateRemotePathFavorite'](arg1, arg2);
}

export function CreateSnippet(arg1) {
  return window['go']['bridge']['Desktop']['CreateSnippet'](arg1);
}

export function CreateTunnel(arg1) {
  return window['go']['bridge']['Desktop']['CreateTunnel'](arg1);
}

export function CreateWorkspaceLayout(arg1) {
  return window['go']['bridge']['Desktop']['CreateWorkspaceLayout'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['bridge']['Desktop']['DeleteProfile'](arg1);
}

export function DeleteRemotePath(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['DeleteRemotePath'](arg1, arg2, arg3);
}

export function DeleteRemotePathFavorite(arg1) {
  return window['go']['bridge']['Desktop']['DeleteRemotePathFavorite'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['bridge']['Desktop']['DeleteSnippet'](arg1);
}

export function DeleteTunnel(arg1) {
  return window['go']['bridge']['Desktop']['DeleteTunnel'](arg1);
}

export function DeleteWorkspaceLayout(arg1) {
  return window['go']['bridge']['Desktop']['DeleteWorkspaceLayout'](arg1);
}

export function DiscardTransferResume(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['DiscardTransferResume'](arg1, arg2, arg3);
}

export function DuplicateProfile(arg1) {
  return window['go']['bridge']['Desktop']['DuplicateProfile'](arg1);
}

export function ExportProfiles() {
  return window['go']['bridge']['Desktop']['ExportProfiles']();
}

export function ExportTerminalText(arg1, arg2) {
  return window['go']['bridge']['Desktop']['ExportTerminalText'](arg1, arg2);
}

export function GetNotificationStatus() {
  return window['go']['bridge']['Desktop']['GetNotificationStatus']();
}

export function GetSettings() {
  return window['go']['bridge']['Desktop']['GetSettings']();
}

export function ImportProfiles() {
  return window['go']['bridge']['Desktop']['ImportProfiles']();
}

export function InspectQuickSSHAuthentication(arg1, arg2) {
  return window['go']['bridge']['Desktop']['InspectQuickSSHAuthentication'](arg1, arg2);
}

export function InspectSSHAuthentication(arg1, arg2) {
  return window['go']['bridge']['Desktop']['InspectSSHAuthentication'](arg1, arg2);
}

export function ListProfiles() {
  return window['go']['bridge']['Desktop']['ListProfiles']();
}

export function ListRemoteFiles(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['ListRemoteFiles'](arg1, arg2, arg3);
}

export function ListRemotePathFavorites() {
  return window['go']['bridge']['Desktop']['ListRemotePathFavorites']();
}

export function ListSnippets() {
  return window['go']['bridge']['Desktop']['ListSnippets']();
}

export function ListTransferResumes(arg1, arg2) {
  return window['go']['bridge']['Desktop']['ListTransferResumes'](arg1, arg2);
}

export function ListTransfers(arg1) {
  return window['go']['bridge']['Desktop']['ListTransfers'](arg1);
}

export function ListTunnelStates(arg1) {
  return window['go']['bridge']['Desktop']['ListTunnelStates'](arg1);
}

export function ListTunnels() {
  return window['go']['bridge']['Desktop']['ListTunnels']();
}

export function ListWorkspaceLayouts() {
  return window['go']['bridge']['Desktop']['ListWorkspaceLayouts']();
}

export function OpenLocalTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Desktop']['OpenLocalTerminal'](arg1, arg2, arg3, arg4);
}

export function OpenQuickSSHTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Desktop']['OpenQuickSSHTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function OpenSFTP(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['OpenSFTP'](arg1, arg2, arg3);
}

export function OpenSSHTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Desktop']['OpenSSHTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function ProbeQuickSSHHostKey(arg1, arg2) {
  return window['go']['bridge']['Desktop']['ProbeQuickSSHHostKey'](arg1, arg2);
}

export function ProbeSSHHostKey(arg1, arg2) {
  return window['go']['bridge']['Desktop']['ProbeSSHHostKey'](arg1, arg2);
}

export function RenameRemotePath(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Desktop']['RenameRemotePath'](arg1, arg2, arg3, arg4);
}

export function RenderSnippet(arg1, arg2) {
  return window['go']['bridge']['Desktop']['RenderSnippet'](arg1, arg2);
}

export function RenewFrontendLease(arg1) {
  return window['go']['bridge']['Desktop']['RenewFrontendLease'](arg1);
}

export function RequestNotificationPermission() {
  return window['go']['bridge']['Desktop']['RequestNotificationPermission']();
}

export function ResetSettings() {
  return window['go']['bridge']['Desktop']['ResetSettings']();
}

export function ResizeTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Desktop']['ResizeTerminal'](arg1, arg2, arg3, arg4, arg5);
}

export function ResumeTransfer(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['ResumeTransfer'](arg1, arg2, arg3);
}

export function SendTestNotification() {
  return window['go']['bridge']['Desktop']['SendTestNotification']();
}

export function SessionLoggingStatus(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['SessionLoggingStatus'](arg1, arg2, arg3);
}

export function StartDownload(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['StartDownload'](arg1, arg2, arg3);
}

export function StartSessionLogging(arg1, arg2, arg3, arg4) {
  return window['go']['bridge']['Desktop']['StartSessionLogging'](arg1, arg2, arg3, arg4);
}

export function StartTunnel(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['StartTunnel'](arg1, arg2, arg3);
}

export function StartUpload(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['StartUpload'](arg1, arg2, arg3);
}

export function StopSessionLogging(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['StopSessionLogging'](arg1, arg2, arg3);
}

export function StopTunnel(arg1, arg2) {
  return window['go']['bridge']['Desktop']['StopTunnel'](arg1, arg2);
}

export function TrustSSHHostKey(arg1, arg2, arg3) {
  return window['go']['bridge']['Desktop']['TrustSSHHostKey'](arg1, arg2, arg3);
}

export function UpdateProfile(arg1) {
  return window['go']['bridge']['Desktop']['UpdateProfile'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['bridge']['Desktop']['UpdateSettings'](arg1);
}

export function UpdateSnippet(arg1) {
  return window['go']['bridge']['Desktop']['UpdateSnippet'](arg1);
}

export function UpdateTunnel(arg1) {
  return window['go']['bridge']['Desktop']['UpdateTunnel'](arg1);
}

export function UpdateWorkspaceLayout(arg1) {
  return window['go']['bridge']['Desktop']['UpdateWorkspaceLayout'](arg1);
}

export function WriteTerminal(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['bridge']['Desktop']['WriteTerminal'](arg1, arg2, arg3, arg4, arg5);
}
