// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';
import {terminalbenchmark} from '../models';
import {tunnel} from '../models';
import {session} from '../models';
import {filetransfer} from '../models';

export function AcknowledgeTerminalOutput(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function ActivateTerminal(arg1:string,arg2:string,arg3:number):Promise<void>;

export function AttachFrontend(arg1:string):Promise<bridge.FrontendLeaseDTO>;

export function AwaitReady():Promise<void>;

export function CancelTransfer(arg1:string,arg2:string):Promise<void>;

export function ChmodRemotePath(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function CloseSFTP(arg1:string,arg2:string):Promise<void>;

export function CloseTerminal(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CompleteTerminalBenchmark(arg1:string,arg2:terminalbenchmark.Report):Promise<terminalbenchmark.Report>;

export function CompleteTerminalSoak(arg1:string,arg2:terminalbenchmark.SoakReport):Promise<terminalbenchmark.SoakReport>;

export function ConfirmApplicationClose(arg1:string):Promise<void>;

export function CreateProfile(arg1:bridge.ProfileInputDTO):Promise<bridge.ProfileDTO>;

export function CreateRemoteDirectory(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateRemotePathFavorite(arg1:string,arg2:string):Promise<bridge.RemotePathFavoriteDTO>;

export function CreateSnippet(arg1:bridge.SnippetInputDTO):Promise<bridge.SnippetDTO>;

export function CreateTunnel(arg1:bridge.TunnelInputDTO):Promise<tunnel.Config>;

export function CreateWorkspaceLayout(arg1:bridge.WorkspaceLayoutInputDTO):Promise<bridge.WorkspaceLayoutDTO>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRemotePath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteRemotePathFavorite(arg1:string):Promise<void>;

export function DeleteSnippet(arg1:string):Promise<void>;

export function DeleteTunnel(arg1:string):Promise<void>;

export function DeleteWorkspaceLayout(arg1:string):Promise<void>;

export function DiscardTransferResume(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DuplicateProfile(arg1:string):Promise<bridge.ProfileDTO>;

export function ExportProfiles():Promise<bridge.ProfileExportDTO>;

export function ExportTerminalText(arg1:string,arg2:string):Promise<bridge.TerminalTextExportDTO>;

export function GetBuildInfo():Promise<bridge.BuildInfoDTO>;

export function GetNotificationStatus():Promise<bridge.NotificationStatusDTO>;

export function GetSettings():Promise<bridge.SettingsDTO>;

export function GetTerminalBenchmarkConfig():Promise<terminalbenchmark.Configuration>;

export function GetTerminalDiagnostics(arg1:string,arg2:string,arg3:number):Promise<session.Diagnostics>;

export function ImportProfiles():Promise<bridge.ProfileImportDTO>;

export function InspectQuickSSHAuthentication(arg1:string,arg2:bridge.QuickSSHInputDTO):Promise<bridge.SSHAuthenticationDTO>;

export function InspectSSHAuthentication(arg1:string,arg2:string):Promise<bridge.SSHAuthenticationDTO>;

export function ListProfiles():Promise<Array<bridge.ProfileDTO>>;

export function ListRemoteFiles(arg1:string,arg2:string,arg3:string):Promise<Array<filetransfer.Entry>>;

export function ListRemotePathFavorites():Promise<Array<bridge.RemotePathFavoriteDTO>>;

export function ListSnippets():Promise<Array<bridge.SnippetDTO>>;

export function ListTransferResumes(arg1:string,arg2:string):Promise<Array<filetransfer.TransferResume>>;

export function ListTransfers(arg1:string):Promise<Array<filetransfer.Transfer>>;

export function ListTunnelStates(arg1:string):Promise<Array<tunnel.Snapshot>>;

export function ListTunnels():Promise<Array<tunnel.Config>>;

export function ListWorkspaceLayouts():Promise<Array<bridge.WorkspaceLayoutDTO>>;

export function OpenLocalTerminal(arg1:string,arg2:string,arg3:number,arg4:number):Promise<session.Session>;

export function OpenQuickSSHTerminal(arg1:string,arg2:bridge.QuickSSHInputDTO,arg3:number,arg4:number,arg5:bridge.SSHCredentialsDTO):Promise<session.Session>;

export function OpenSFTP(arg1:string,arg2:string,arg3:bridge.SSHCredentialsDTO):Promise<filetransfer.Session>;

export function OpenSSHTerminal(arg1:string,arg2:string,arg3:number,arg4:number,arg5:bridge.SSHCredentialsDTO):Promise<session.Session>;

export function OpenTerminalBenchmark(arg1:string,arg2:number,arg3:number):Promise<session.Session>;

export function ProbeQuickSSHHostKey(arg1:string,arg2:bridge.QuickSSHInputDTO):Promise<bridge.QuickSSHProbeDTO>;

export function ProbeSSHHostKey(arg1:string,arg2:string):Promise<bridge.SSHHostKeyDTO>;

export function RecordTerminalBenchmarkProgress(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RenameRemotePath(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RenderSnippet(arg1:string,arg2:Record<string, string>):Promise<bridge.SnippetPreviewDTO>;

export function RenewFrontendLease(arg1:string):Promise<bridge.FrontendLeaseDTO>;

export function RequestNotificationPermission():Promise<bridge.NotificationStatusDTO>;

export function ResetSettings():Promise<bridge.SettingsDTO>;

export function ResizeTerminal(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number):Promise<void>;

export function ResumeTransfer(arg1:string,arg2:string,arg3:string):Promise<filetransfer.Transfer>;

export function SendTestNotification():Promise<void>;

export function SessionLoggingStatus(arg1:string,arg2:string,arg3:number):Promise<session.SessionLogStatus>;

export function StartDownload(arg1:string,arg2:string,arg3:string):Promise<filetransfer.Transfer>;

export function StartSessionLogging(arg1:string,arg2:string,arg3:number,arg4:boolean):Promise<session.SessionLogStatus>;

export function StartTunnel(arg1:string,arg2:string,arg3:bridge.SSHCredentialsDTO):Promise<tunnel.Snapshot>;

export function StartUpload(arg1:string,arg2:string,arg3:string):Promise<filetransfer.Transfer>;

export function StopSessionLogging(arg1:string,arg2:string,arg3:number):Promise<session.SessionLogStatus>;

export function StopTunnel(arg1:string,arg2:string):Promise<void>;

export function TrustSSHHostKey(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function UpdateProfile(arg1:bridge.ProfileInputDTO):Promise<bridge.ProfileDTO>;

export function UpdateSettings(arg1:bridge.SettingsDTO):Promise<bridge.SettingsDTO>;

export function UpdateSnippet(arg1:bridge.SnippetInputDTO):Promise<bridge.SnippetDTO>;

export function UpdateTunnel(arg1:bridge.TunnelInputDTO):Promise<tunnel.Config>;

export function UpdateWorkspaceLayout(arg1:bridge.WorkspaceLayoutInputDTO):Promise<bridge.WorkspaceLayoutDTO>;

export function WriteTerminal(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;
